### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by tomysshadow** [Brian151/OpenShockwave#1]
I don't currently have any way of contacting you (Brian151) so that we can collaborate on this project.

**Comment by Brian151** [comment]
and i greatly dislike sharing certain info...
Alright, what options are available to you?

**Comment by tomysshadow** [comment]
Many, I have Trillian, Discord, Google, Skype, AIM... maybe I could create a temporary email and you can send your details there, since I'd prefer not to publicly share my real email either.

**Comment by Brian151** [comment]
I have been unable to use skype in a while... last time I used it, also wasn't super impressed.
Problem is google still ends-up sharing email, iirc
Heard of Discord...
I thought AIM was practically an ancient relic?
Never heard of Trillian

**Comment by tomysshadow** [comment]
What would you prefer to do then?

**Comment by Brian151** [comment]
I'll have to work that out.
I do have youtube and deviantart accounts, also.
(I distrust youtube, though, their new system sucks and it's all too easy to miss stuff. specifically private messages)
It's getting a bit late/early for me.
And I actually exhausted much mental energy on either arguments or this file format... /:

**Comment by tomysshadow** [comment]
Oh, you can send me a deviantArt message, tomysshadow is my username on there. I know my page isn't that stunning.

**Comment by Brian151** [comment]
lol...mine ain't no piece of art, either... it hasn't exactly been updated in well... umm... i'm not sure, a few years... ? XD i'll go do that then...

**Comment by Brian151** [comment]
and that's sent...longer than planned/expected

**Comment by Brian151** [comment]
also, there are a few things associated with my deviantart account i'd rather not brought-up. besides which, if you do want to know more, i'd rather tell you from my side of things because the other individuals i feel have some rather biased opinions. i've practically isolated my various usernames from eachother after certain events... i'd greatly prefer to forget anything ever happened. anyways, in case you go poking around my journals or anything. i'll probably head to bed soon. anything else we need to discuss right here?

**Comment by tomysshadow** [comment]
I just replied, nothing else to discuss here. I'll try and look into the format more. Maybe I'll upload some DXRs to inspect to the repo. Goodnight

**Comment by Brian151** [comment]
night. and umm, careful with that. not entirely sure what the creators of said dxrs would say of it! i'm waiting on ex gamelab employees concerning uploading a diropened movie from one oftheir games. (or singificant portions of it) what games they from?

**Comment by tomysshadow** [comment]
Well, one great game to test with is MYLK because it's a series of simple DXR files which are big-endian so the letters aren't backwards and it says in the readme "this project is not for profit.  It may be distributed freely." There's also Pet WONKAnite which is a free download from Tucows, it's also DXR so again it might be worth looking at.

**Comment by Brian151** [comment]
oh, alright then. there's a few dxr's i have but i dare not share them publicly. ever heard of powerwheels offroad adventure? (funny story: i diropened it, my friend couldn't open it in director... it just crashed the whole program. he said there were interesting labels in there, too... perhaps indicating the devs predicted someone trying to bust their game open...lol) tucows dl's i'm a little iffy about, cuz it's just "abandonware" , iirc, but first seems alright.

**Comment by Brian151** [comment]
i think for now this has served its purpose
