### ISSUE TITLE
lscrtoscript broken after last merge ?

### ISSUE THREAD

**Issue by ThuGie** [Brian151/OpenShockwave#13]
Hey guys,

I saw the huge merge, was like got to try it out.
Only to get a error. disabling that part gave way to more and more errors.
Might wanna check the merge out.. and see whats wrong.

**Comment by djsrv** [comment]
What error are you getting? It uses some ES6 features like classes and arrow functions which are supported by the latest versions of Firefox, Chrome, and Edge, but not Safari, IE, and some alternative browsers.

**Comment by ThuGie** [comment]
Using chrome and let me see

`Uncaught TypeError: argList.shift is not a function
    at Object.callobj (projectorrays.js:1401)
    at Bytecode.translate (projectorrays.js:1412)
    at Handler.translate (projectorrays.js:744)
    at LingoScript.translate (projectorrays.js:566)
    at OpenShockwaveMovie.linkScripts (projectorrays.js:168)
    at FileReader.reader.onload.e (projectorrays.js:96)`

after i disable that piece of code i get
`projectorrays.js:1167 Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.call_local (projectorrays.js:1167)
    at Bytecode.translate (projectorrays.js:1412)
    at Handler.translate (projectorrays.js:744)
    at LingoScript.translate (projectorrays.js:566)
    at OpenShockwaveMovie.linkScripts (projectorrays.js:168)
    at FileReader.reader.onload.e (projectorrays.js:96)
call_local @ projectorrays.js:1167
Bytecode.translate @ projectorrays.js:1412
Handler.translate @ projectorrays.js:744
LingoScript.translate @ projectorrays.js:566
OpenShockwaveMovie.linkScripts @ projectorrays.js:168
reader.onload.e @ projectorrays.js:96`

again after disabling that one as well

`projectorrays.js:1133 Uncaught TypeError: Cannot read property 'getIndex' of undefined
    at Object.jmp (projectorrays.js:1133)
    at Bytecode.translate (projectorrays.js:1412)
    at Handler.translate (projectorrays.js:744)
    at LingoScript.translate (projectorrays.js:566)
    at OpenShockwaveMovie.linkScripts (projectorrays.js:168)
    at FileReader.reader.onload.e (projectorrays.js:96)
jmp @ projectorrays.js:1133
Bytecode.translate @ projectorrays.js:1412
Handler.translate @ projectorrays.js:744
LingoScript.translate @ projectorrays.js:566
OpenShockwaveMovie.linkScripts @ projectorrays.js:168
reader.onload.e @ projectorrays.js:96`

**Comment by hqkirkland** [comment]
ThuGie: Are you sure that the file was successfully decompressed? I encountered a similar problem, but with a partially-completed decomposition.

**Comment by ThuGie** [comment]
Nope thats not it, redownloaded just now again even though i did already do that twice.
Same problem. tried firefox as well same.

Did you try the version as well or ?
And ofcourse a .dir that does need the calls ?

**Comment by djsrv** [comment]
Could you upload the dir file somewhere?

**Comment by ThuGie** [comment]
[DCR2DIRoutput22.zip](https://github.com/Brian151/OpenShockwave/files/1159734/DCR2DIRoutput22.zip)
Here is the file i tried.

**Comment by hqkirkland** [comment]
ThuGie: I believe this is a Spineworld file you're trying to decompile, game_v440.dcr.

I've never successfully been able to use DCR2DIR to unpack one of the Spineworld files, especially not game_v440.dcr.

I don't think it's actually a complete file.

**Comment by ThuGie** [comment]
oh i have been able to do it multiple times.
But in this case its not really about that right ?
Cause javascript is saying its missing stuff. or like functions dont exist a broken dir file wont make javascript say that ;).

**Comment by djsrv** [comment]
I haven't had time to look at it yet, but a broken dir file is highly probable. The objcall instruction expects an arglist (which implements the shift function) on the stack, but there's a different type there instead. Error handling could definitely be improved though.

**Comment by hqkirkland** [comment]
ThuGie, it WILL make JavaScript say that if they use strict mode, which they do.

**Comment by ThuGie** [comment]
[sdgsdgsdgdd.zip](https://github.com/Brian151/OpenShockwave/files/1162968/sdgsdgsdgdd.zip)
Here is one that does sort of decompile though no normal output only in console.

But at end i get

`projectorrays.js:101 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at FileReader.reader.onload.e (file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:101:32)
﻿
​`

seems in firefox i do get a output btw!
Only the first Lscr  ?
And that seems to be the code used to get it to .dir :p

with debug mode on

Constructing Chunk: MDFL
projectorrays.js:179:22
Constructing Chunk: SCRF
projectorrays.js:179:22
ReferenceError: bytecode is not defined
[Learn More]
projectorrays.js:923:22
Bytecode.prototype.translate
file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:923:22
Handler.prototype.translate
file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:746:3
LingoScript.prototype.translate
file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:568:3
OpenShockwaveMovie.prototype.linkScripts
file:///OpenShockwave-master/tools/lscrtoscript/js/projectorrays.js:170:6
OpenShockwaveMovie.prototype.readFile/reader.onload

**Comment by tomysshadow** [comment]
This is because Chrome is dumb and detects JavaScript between two frames on
the same hard drive as cross-origin. It needs to be run on a server or
using something such as XAMPP (I didn't have this provision when I
originally made it because Firefox does this correctly.)

**Comment by ThuGie** [comment]
Ah well thats not really a problem i got both browsers installed, and have a webserver so its fine,
But whats the reason it only tries to decompile the first script it tries ?
Or is it something with this .dir file thats the reason ?

**Comment by djsrv** [comment]
It's because it decompiles all the scripts but nobody's updated that text.

**Comment by tomysshadow** [comment]
It does decompile everything - that text hasn't been changed for months. :S

**Comment by djsrv** [comment]
Here, I've updated it: #14

**Comment by ThuGie** [comment]
Oh i didnt even see that text,
its more about i tried the sdgsdgsdgdd.zip file and only got 1 script out of it, while it should contain more.
unless the converting to .dir failed so badly.

**Comment by djsrv** [comment]
It's because there's only one handler in that file.

**Comment by ThuGie** [comment]
How can i get it so i can get all code out of it ?
Do i have to use something else to get the .dir or is it because the decompiler simply isnt finished yet ?

**Comment by djsrv** [comment]
I don't know how you extracted the dir file, but it's showing all the code there is in it. It can't extract more code than there is in the file.

**Comment by ThuGie** [comment]
So it simply isnt converted correctly.
Will have to try doing it a few diffrent ways see if one works :). thanks a lot.
