### ISSUE TITLE
Is it possible to get where the scripts exactly come from ?

### ISSUE THREAD

**Issue by ThuGie** [Brian151/OpenShockwave#16]
Hey guys,

So once i run a .dir file thru it i can get bits and pieces of code here and there.
Some seem to be exactly like it should be, but now the problem is.
It does't say where from what script it actually comes from it only has like a number.

LctX 129
Lscr 134
Handlers

But no clue if it comes from a script Called Init or Loop etc.
And what is the best way to report the missing codes getting a lot of ERROR or UNK_?

Sample File i get this with
[load_play.zip](https://github.com/Brian151/OpenShockwave/files/1191821/load_play.zip)
Sample File that simply wont load unprotecting no error what so ever, but it refuses to.
Could it be diff version director or something ?
[game_v440.zip](https://github.com/Brian151/OpenShockwave/files/1191825/game_v440.zip)

i might be wrong, but it seems to work..
probably a better way..
projectorrays.js
`        "unk_72": () => {
            translation = new AST.SYS('player');
            script.stack.push(translation);
		},
        "unk_b2": () => {
            if(this.obj == 305)
                var name = 'system';
            if(this.obj == 307)
                var name = 'global';
            else if(this.obj == 309)
                var name = 'key';
            else if(this.obj == 311)
                var name = 'mouse';
            else if(this.obj == 313)
                var name = 'movie';
            else if(this.obj == 303)
                var name = 'sound';
            translation = new AST.SYS(name);
            script.stack.push(translation);
		},`

ast.js

`    class SYS extends Node {
        constructor(value) {
			super();
			this.value = value;
		}
		toString() {
			return "_" + this.value;
		}
	}
	AST.SYS = SYS;`

**Comment by Brian151** [comment]
clarify?

if you mean the names of the scripts, the problem is we haven't yet found a way to associate them...

**Comment by ThuGie** [comment]
Ah i see that is exactly what i was asking,

And for the bit of code provided, is it the right way to do or ?
There is more like there is a UNK_B0 if i recall it only contains a string thats it,
Often at least for the game i am trying its something like gMembers
So just doing
`        "unk_b0": () => {
			var list = script.stack.pop();
            translation = new AST.SYS(list.varName);
            script.stack.push(translation);
		},`

We get gMembers.valuehere and it seems to be fine
as you get 
if gMembers.value = 4 then
stuff like that.
